### ISSUE TITLE
 CUDA runtime implicit initialization on GPU:0 failed. Status: out of memory

### ISSUE THREAD

**Issue by jayaramreddy10** [daipengwa/NeuralPointCloudRendering#5]
Hi,

When i test npcr_ScanNet.py using pretrained checkpoints , I am getting below error message that GPU is out of memory. But I am already using a high end GPU- NVIDIA RTX 2070, is it not sufficient for inference?

Error message: 
load ply time: 25.08699655532837                                                                                                                                                                                   loaded descriptors.                                                                                                                                                                                                Traceback (most recent call last):                                                                                                                                                                                   File "npcr_ScanNet.py", line 69, in <module>                                                                                                                                                                         sess = tf.Session()                                                                                                                                                                                              File "/scratch/jayaram.messi/envs/Neural_pc_rendering_tf/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1551, in __init__                                                                   
super(Session, self).__init__(target, graph, config=config)                                                                                                                                                      File "/scratch/jayaram.messi/envs/Neural_pc_rendering_tf/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 676, in __init__                                                                     
self._session = tf_session.TF_NewSessionRef(self._graph._c_graph, opts)                                                                                                                                        tensorflow.python.framework.errors_impl.InternalError: CUDA runtime implicit initialization on GPU:0 failed. Status: out of memory 

So, how do I avoid this out of memory issue ?

**Comment by daipengwa** [comment]
Hi,
We used 1080Ti, there is no OOM error. I suggest that you can check if the
GPU is occupied by other processes?
Thanks

**Comment by jayaramreddy10** [comment]
Thanks, its resolved now
